import type { ComponentNode, EmittedFile } from "loom-ir";

function lastSlug(id: string): string {
  return id.split("/").pop()!;
}

/**
 * jest-axe check stub per `PatternConformanceNode`/`DeltaNode` (§8). Scoped
 * thin for this pass, same rationale as storybook.ts.
 */
export function emitAxeChecks(component: ComponentNode): EmittedFile[] {
  const nodes = component.a11y.filter((n) => n.kind === "pattern-conformance" || n.kind === "delta");

  return nodes.map((node) => {
    const description =
      node.kind === "pattern-conformance" ? `conforms to APG pattern '${node.pattern}'` : "documents an a11y delta";
    const lines = [
      `// GENERATED by loom-emit-tests (axe backend, structural stub).`,
      `// Node '${node.id}': ${description}.`,
      `import { axe, toHaveNoViolations } from "jest-axe";`,
      `expect.extend(toHaveNoViolations);`,
      ``,
      `it(${JSON.stringify(`[${node.id}] a11y conformance`)}, async () => {`,
      `  // TODO: render '${component.name}' into a container and run axe(container)`,
      `});`,
      ``,
    ];
    return { path: `${component.name}.${lastSlug(node.id)}.axe.test.ts`, contents: lines.join("\n") };
  });
}
