import type { ComponentNode, EmittedFile } from "loom-ir";

/**
 * Builds the runtime `{ states, transitions }` machine literal embedded in
 * the emitted file. Deliberately doesn't include `stateType`/`transitionType`
 * (part of loom-expr's `MachineContext`) — those are only consulted by
 * `typecheck`, which never runs inside an emitted test; `evaluate` and
 * `domainToArbitrary` only ever read `.states`/`.transitions` at runtime.
 */
function machineLiteral(component: ComponentNode): string {
  const states = component.states.map((s) => ({ id: s.name, ...s.flags }));
  const transitions = component.transitions.map((t) => ({ id: t.name, from: t.from, to: t.to }));
  return JSON.stringify({ states, transitions });
}

function defaultEnvLiteral(component: ComponentNode): string {
  const env: Record<string, unknown> = {};
  for (const decl of component.declarations) {
    if (decl.kind === "prop" && decl.defaultValue !== undefined) env[decl.name] = decl.defaultValue;
  }
  return JSON.stringify(env);
}

/**
 * Emits Jest-style unit tests for `InvariantNode`s and fast-check property
 * tests for `PropertyNode`s (§8). Every test name embeds the originating
 * node id (§5.5) so a results ledger keyed by that id can be joined back.
 *
 * The emitted file ships the predicate/domain ASTs as embedded JSON and
 * re-runs them through loom-expr's own `evaluate`/`domainToArbitrary` at test
 * time, rather than transpiling each expression into bespoke JS — one
 * interpreter, reused for both compile-time checks and generated tests.
 */
export function emitJestTests(component: ComponentNode): EmittedFile[] {
  const invariants = component.claims.filter((c) => c.kind === "invariant");
  const properties = component.claims.filter((c) => c.kind === "property");
  if (invariants.length === 0 && properties.length === 0) return [];

  const lines: string[] = [
    `// GENERATED by loom-emit-tests. Do not edit by hand.`,
    `import { evaluate, domainToArbitrary } from "loom-expr";`,
    `import fc from "fast-check";`,
    ``,
    `const __machine: any = ${machineLiteral(component)};`,
    `const __defaultEnv: any = ${defaultEnvLiteral(component)};`,
    ``,
    `describe(${JSON.stringify(component.name)}, () => {`,
  ];

  for (const claim of invariants) {
    lines.push(`  it(${JSON.stringify(`[${claim.id}] invariant`)}, () => {`);
    lines.push(`    const predicate = ${JSON.stringify(claim.predicate)};`);
    lines.push(`    expect(evaluate(predicate, __defaultEnv, { machine: __machine })).toBe(true);`);
    lines.push(`  });`);
  }

  for (const claim of properties) {
    lines.push(`  it(${JSON.stringify(`[${claim.id}] property`)}, () => {`);
    lines.push(`    const domain = ${JSON.stringify(claim.domain)};`);
    lines.push(`    const predicate = ${JSON.stringify(claim.predicate)};`);
    lines.push(`    const arb = domainToArbitrary(domain, { machine: __machine, env: __defaultEnv });`);
    lines.push(`    fc.assert(`);
    lines.push(`      fc.property(arb, (value) =>`);
    lines.push(
      `        evaluate(predicate, { ...__defaultEnv, ${JSON.stringify(claim.ident)}: value }, { machine: __machine }) === true`
    );
    lines.push(`      )`);
    lines.push(`    );`);
    lines.push(`  });`);
  }

  lines.push(`});`, ``);

  return [{ path: `${component.name}.jest.test.ts`, contents: lines.join("\n") }];
}
