import type { ComponentNode, EmittedFile } from "loom-ir";

/**
 * Builds the runtime `{ states, transitions }` machine literal embedded in
 * the emitted file. Deliberately doesn't include `stateType`/`transitionType`
 * (part of loom-expr's `MachineContext`) — those are only consulted by
 * `typecheck`, which never runs inside an emitted test; `evaluate` and
 * `domainToArbitrary` only ever read `.states`/`.transitions` at runtime.
 */
function machineLiteral(component: ComponentNode): string {
  const states = component.states.map((s) => ({ id: s.name, ...s.flags }));
  const transitions = component.transitions.map((t) => ({ id: t.name, from: t.from, to: t.to }));
  return JSON.stringify({ states, transitions });
}

/**
 * The free-input baseline: prop defaults plus field initial values. A
 * field's own `<name>Valid` boolean and any `derived` value are computed at
 * test-run time instead (see `valueGraphLines`), since they depend on
 * whichever value a property test is currently sampling for its bound
 * ident — this literal only ever holds the static starting point.
 */
function defaultEnvLiteral(component: ComponentNode): string {
  const env: Record<string, unknown> = {};
  for (const decl of component.declarations) {
    if (decl.kind === "prop" && decl.defaultValue !== undefined) env[decl.name] = decl.defaultValue;
    if (decl.kind === "field") env[decl.name] = decl.initialValue ?? "";
  }
  return JSON.stringify(env);
}

/**
 * Emits the `__buildEnv` helper that closes a sampled/default env over the
 * component's own value graph — every field's own `<name>Valid` and every
 * `derived` value's current result — mirroring exactly what emitReact's
 * `valueEnvParts`/emitAngular's `envLiteral` compute at render time. This is
 * what lets a claim's `predicate` reference a `derived` value by name
 * instead of only the raw props/fields a property test samples — "the claim
 * language reaching the value graph."
 *
 * Only emitted when the component actually declares a field or a `derived`
 * value; a plain-props component's claims still evaluate directly against
 * `{ ...__defaultEnv, [ident]: value }`, exactly as before this addition.
 */
function valueGraphLines(component: ComponentNode): string[] {
  const fields = component.declarations.filter((d) => d.kind === "field");
  const derivedValues = component.declarations.filter((d) => d.kind === "derived");
  if (fields.length === 0 && derivedValues.length === 0) return [];

  return [
    `const __fields: any = ${JSON.stringify(fields.map((f) => ({ name: f.name, validate: f.validate ?? null })))};`,
    `const __derived: any = ${JSON.stringify(derivedValues.map((d) => ({ name: d.name, expr: d.expr })))};`,
    `function __buildEnv(overrides: any): any {`,
    `  const env: any = { ...__defaultEnv, ...overrides };`,
    `  for (const f of __fields) env[f.name + "Valid"] = f.validate ? evaluate(f.validate, { [f.name]: env[f.name] }) === true : true;`,
    `  for (const d of __derived) env[d.name] = evaluate(d.expr, env);`,
    `  return env;`,
    `}`,
  ];
}

/**
 * Emits Jest-style unit tests for `InvariantNode`s and fast-check property
 * tests for `PropertyNode`s (§8). Every test name embeds the originating
 * node id (§5.5) so a results ledger keyed by that id can be joined back.
 *
 * The emitted file ships the predicate/domain ASTs as embedded JSON and
 * re-runs them through loom-expr's own `evaluate`/`domainToArbitrary` at test
 * time, rather than transpiling each expression into bespoke JS — one
 * interpreter, reused for both compile-time checks and generated tests.
 */
export function emitJestTests(component: ComponentNode): EmittedFile[] {
  const invariants = component.claims.filter((c) => c.kind === "invariant");
  const properties = component.claims.filter((c) => c.kind === "property");
  if (invariants.length === 0 && properties.length === 0) return [];

  const envLines = valueGraphLines(component);
  const hasValueGraph = envLines.length > 0;
  const invariantEnv = hasValueGraph ? "__buildEnv({})" : "__defaultEnv";

  const lines: string[] = [
    `// GENERATED by loom-emit-tests. Do not edit by hand.`,
    `import { evaluate, domainToArbitrary } from "loom-expr";`,
    `import fc from "fast-check";`,
    ``,
    `const __machine: any = ${machineLiteral(component)};`,
    `const __defaultEnv: any = ${defaultEnvLiteral(component)};`,
    ...(hasValueGraph ? [``, ...envLines] : []),
    ``,
    `describe(${JSON.stringify(component.name)}, () => {`,
  ];

  for (const claim of invariants) {
    lines.push(`  it(${JSON.stringify(`[${claim.id}] invariant`)}, () => {`);
    lines.push(`    const predicate = ${JSON.stringify(claim.predicate)};`);
    lines.push(`    expect(evaluate(predicate, ${invariantEnv}, { machine: __machine })).toBe(true);`);
    lines.push(`  });`);
  }

  for (const claim of properties) {
    lines.push(`  it(${JSON.stringify(`[${claim.id}] property`)}, () => {`);
    lines.push(`    const domain = ${JSON.stringify(claim.domain)};`);
    lines.push(`    const predicate = ${JSON.stringify(claim.predicate)};`);
    lines.push(`    const arb = domainToArbitrary(domain, { machine: __machine, env: __defaultEnv });`);
    lines.push(`    fc.assert(`);
    lines.push(`      fc.property(arb, (value) =>`);
    const propertyEnv = hasValueGraph
      ? `__buildEnv({ ${JSON.stringify(claim.ident)}: value })`
      : `{ ...__defaultEnv, ${JSON.stringify(claim.ident)}: value }`;
    lines.push(`        evaluate(predicate, ${propertyEnv}, { machine: __machine }) === true`);
    lines.push(`      )`);
    lines.push(`    );`);
    lines.push(`  });`);
  }

  lines.push(`});`, ``);

  return [{ path: `${component.name}.jest.test.ts`, contents: lines.join("\n") }];
}
