import type { ComponentNode, EmittedFile } from "loom-ir";

function lastSlug(id: string): string {
  return id.split("/").pop()!;
}

/**
 * Storybook play-function stub per `ScenarioNode` (§8). Scoped thin for this
 * pass (§14 step 4 focuses on the Jest+fast-check backend proving the
 * language round-trips first) — this emits a real, structurally valid file
 * per scenario, but doesn't yet render the component or assert per-hop state.
 */
export function emitStorybookPlay(component: ComponentNode): EmittedFile[] {
  const scenarios = component.claims.filter((c) => c.kind === "scenario");

  return scenarios.map((scenario) => {
    const lines = [
      `// GENERATED by loom-emit-tests (Storybook backend, structural stub).`,
      `// [${scenario.id}] ${scenario.from} --${JSON.stringify(scenario.events)}--> ${scenario.to}`,
      `// TODO: render '${component.name}' and drive/assert each hop; currently checked`,
      `// only at compile time (loom-ir's checkScenario) that this scenario traces real transitions.`,
      `export const play = async ({ canvasElement }: { canvasElement: HTMLElement }) => {`,
      `  void canvasElement;`,
      `};`,
      ``,
    ];
    return { path: `${component.name}.${lastSlug(scenario.id)}.stories.play.ts`, contents: lines.join("\n") };
  });
}
