import type { ComponentNode, EmittedFile } from "loom-ir";

function lastSlug(id: string): string {
  return id.split("/").pop()!;
}

/**
 * Storybook play-function stub per `PathNode` (§8). Scoped thin for this
 * pass (§14 step 4 focuses on the Jest+fast-check backend proving the
 * language round-trips first) — this emits a real, structurally valid file
 * per path, but doesn't yet render the component or assert per-hop state.
 */
export function emitStorybookPlay(component: ComponentNode): EmittedFile[] {
  const paths = component.claims.filter((c) => c.kind === "path");

  return paths.map((path) => {
    const lines = [
      `// GENERATED by loom-emit-tests (Storybook backend, structural stub).`,
      `// [${path.id}] ${path.from} --${JSON.stringify(path.events)}--> ${path.to}`,
      `// TODO: render '${component.name}' and drive/assert each hop; currently checked`,
      `// only at compile time (loom-ir's checkPath) that this path traces real transitions.`,
      `export const play = async ({ canvasElement }: { canvasElement: HTMLElement }) => {`,
      `  void canvasElement;`,
      `};`,
      ``,
    ];
    return { path: `${component.name}.${lastSlug(path.id)}.stories.play.ts`, contents: lines.join("\n") };
  });
}
