import type { ComponentNode, EmittedFile, TokenRefNode } from "loom-ir";

function lastSlug(id: string): string {
  return id.split("/").pop()!;
}

/**
 * Cheap, deterministic conformance check per `TokenRefNode` (§8's `'unit'`
 * tier): re-runs the *actual* loom-emit-styles CSS backend against just this
 * node and asserts the resulting stylesheet contains the expected
 * `property: var(--token)` declaration — real conformance against the real
 * backend, not a hand-duplicated string match, same "one interpreter reused
 * everywhere" approach jest.ts already uses for loom-expr. Full pixel-diff
 * visual regression against `VisualConformanceNode` (§8's Chromatic row) is
 * a separate, deliberately unbuilt tier — this only covers the cheap,
 * always-runnable check.
 */
export function emitTokenConformanceTests(component: ComponentNode): EmittedFile[] {
  const tokenRefs = component.style.filter((n): n is TokenRefNode => n.kind === "token-ref");

  return tokenRefs.map((node) => {
    const singleNodeComponent = { name: component.name, style: [node] };
    const lines = [
      `// GENERATED by loom-emit-tests (style backend). Do not edit by hand.`,
      `import { emitComponentCss, tokenCssVar } from "loom-emit-styles";`,
      ``,
      `const __component: any = ${JSON.stringify(singleNodeComponent)};`,
      ``,
      `it(${JSON.stringify(`[${node.id}] token conformance`)}, () => {`,
      `  const css = emitComponentCss(__component).contents;`,
      `  expect(css).toContain(\`${node.property}: var(\${tokenCssVar(${JSON.stringify(node.token)})});\`);`,
      `});`,
      ``,
    ];
    return { path: `${component.name}.${lastSlug(node.id)}.style.test.ts`, contents: lines.join("\n") };
  });
}
