import type { ComponentNode, EmittedFile } from "loom-ir";
import { loomTypeToTs } from "./loomTypeToTs.js";

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}

function pascalCase(slug: string): string {
  return slug.split("-").map(capitalize).join("");
}

function machineLiteral(component: ComponentNode): string {
  const states = component.states.map((s) => ({ id: s.name, ...s.flags }));
  const transitions = component.transitions.map((t) => ({
    id: t.name,
    from: t.from,
    to: t.to,
    trigger: t.trigger,
    guard: t.guard ?? null,
  }));
  return JSON.stringify({ states, transitions });
}

/**
 * Compiles a `ComponentNode` to a minimal standalone Angular component
 * (§4/§14 step 7 — the second framework target, and the real test of
 * whether the IR is genuinely framework-agnostic).
 *
 * Deliberately mirrors loom-emit-react's strategy exactly: the same
 * `Declarations` nodes become typed `@Input`/`@Output` members, the same
 * embedded machine is driven at runtime through loom-expr's `evaluate`, and
 * `MethodNode` is skipped the same way. Only the framework idiom differs
 * (decorators + a template string vs. JSX) — porting cost was a rename of
 * the surface syntax, not a redesign, which is the concrete evidence for
 * §4's "one IR, many targets" claim.
 */
export function emitAngular(component: ComponentNode): EmittedFile[] {
  const componentName = pascalCase(component.name);
  const selector = `loom-${component.name}`;
  const unsupported = component.declarations.filter((d) => d.kind === "method");
  for (const node of unsupported) {
    // eslint-disable-next-line no-console
    console.warn(`[loom-emit-angular] '${node.id}' (kind: method) is unsupported by this backend; skipped.`);
  }

  const props = component.declarations.filter((d) => d.kind === "prop");
  const events = component.declarations.filter((d) => d.kind === "event");
  const slots = component.declarations.filter((d) => d.kind === "slot");
  const pattern = component.a11y.find((n) => n.kind === "pattern-conformance");
  const disabledProp = props.find((p) => p.name === "disabled");
  const hasMachine = component.states.length > 0;

  const lines: string[] = [
    `// GENERATED by loom-emit-angular. Do not edit by hand.`,
    unsupported.length > 0
      ? `// Unsupported by this backend: ${unsupported.map((n) => n.id).join(", ")}`
      : undefined,
    `import { Component, EventEmitter, Input, Output } from "@angular/core";`,
    hasMachine ? `import { evaluate } from "loom-expr";` : undefined,
    ``,
  ].filter((l): l is string => l !== undefined);

  if (hasMachine) {
    lines.push(`const __machine: any = ${machineLiteral(component)};`, ``);
  }

  // Static string values are bound as single-quoted TS literals inside the
  // double-quoted HTML attribute value — reusing JSON.stringify (double
  // quotes) here would collide with the surrounding template-string quoting.
  const attrs: string[] = [`[attr.data-loom-component]="'${component.name}'"`];
  if (hasMachine) attrs.push(`[attr.data-state]="state"`);
  if (pattern) attrs.push(`[attr.role]="'${pattern.pattern}'"`);
  if (disabledProp) attrs.push(`[attr.aria-disabled]="disabled"`);
  if (hasMachine) attrs.push(`(click)="dispatch('click')"`);
  const templateBody = slots.some((s) => s.name === "default") ? "<ng-content></ng-content>" : "";
  const template = `<div ${attrs.join(" ")}>${templateBody}</div>`;

  lines.push(`@Component({`);
  lines.push(`  selector: ${JSON.stringify(selector)},`);
  lines.push(`  standalone: true,`);
  lines.push(`  template: \`${template}\`,`);
  lines.push(`})`);
  lines.push(`export class ${componentName}Component {`);

  for (const prop of props) {
    lines.push(`  /** ${prop.id} */`);
    lines.push(`  @Input() ${prop.name}: ${loomTypeToTs(prop.valueType)} = ${JSON.stringify(prop.defaultValue ?? null)};`);
  }
  for (const event of events) {
    lines.push(`  /** ${event.id} */`);
    lines.push(`  @Output() ${event.name} = new EventEmitter<${loomTypeToTs(event.payloadType)}>();`);
  }

  if (hasMachine) {
    lines.push(`  state: string = __machine.states[0]?.id;`);
    lines.push(``);
    lines.push(`  dispatch(eventName: string): void {`);
    lines.push(`    const env: any = { ${props.map((p) => `${p.name}: this.${p.name}`).join(", ")} };`);
    lines.push(`    const transition = __machine.transitions.find(`);
    lines.push(
      `      (t: any) => t.from === this.state && t.trigger?.kind === "event" && t.trigger?.name === eventName && (!t.guard || evaluate(t.guard, env) === true)`
    );
    lines.push(`    );`);
    lines.push(`    if (transition) this.state = transition.to;`);
    lines.push(`  }`);
  }

  lines.push(`}`, ``);

  return [{ path: `${componentName}.component.ts`, contents: lines.join("\n") }];
}
