import type { ComponentNode, EmittedFile } from "loom-ir";
import { loomTypeToTs } from "./loomTypeToTs.js";

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}

function pascalCase(slug: string): string {
  return slug.split("-").map(capitalize).join("");
}

/** Slot/prop names come from spec slugs and may contain hyphens, which aren't valid in a JS identifier. */
function camelCase(slug: string): string {
  const [first, ...rest] = slug.split("-");
  return [first, ...rest.map(capitalize)].join("");
}

/** The default slot maps to React's built-in `children`; every other slot becomes its own named prop. */
function slotPropName(slotName: string): string {
  return slotName === "default" ? "children" : camelCase(slotName);
}

function machineLiteral(component: ComponentNode): string {
  const states = component.states.map((s) => ({ id: s.name, ...s.flags }));
  const transitions = component.transitions.map((t) => ({
    id: t.name,
    from: t.from,
    to: t.to,
    trigger: t.trigger,
    guard: t.guard ?? null,
  }));
  return JSON.stringify({ states, transitions });
}

/**
 * Compiles a `ComponentNode` to a minimal React function component (§4/§14
 * step 5 — the first framework target).
 *
 * Declarations become a typed props interface. A `SlotNode` named
 * `"default"` maps to React's built-in `children`; any other slot becomes
 * its own `React.ReactNode` prop. If the component has a machine, it's
 * embedded as data and driven at runtime through loom-expr's `evaluate` —
 * the same interpreter loom-emit-tests reuses for generated tests — rather
 * than transpiling each guard into bespoke JS. Only a generic `click`
 * interaction is wired up for now (key/pointer triggers are a backend
 * TODO); `MethodNode`s have no React rendering strategy yet and are
 * skipped rather than failing the whole emission (§14 step 5's "skip,
 * don't throw" contract).
 */
export function emitReact(component: ComponentNode): EmittedFile[] {
  const componentName = pascalCase(component.name);
  const unsupported = component.declarations.filter((d) => d.kind === "method");
  for (const node of unsupported) {
    // eslint-disable-next-line no-console
    console.warn(`[loom-emit-react] '${node.id}' (kind: method) is unsupported by this backend; skipped.`);
  }

  const props = component.declarations.filter((d) => d.kind === "prop");
  const events = component.declarations.filter((d) => d.kind === "event");
  const slots = component.declarations.filter((d) => d.kind === "slot");
  const pattern = component.a11y.find((n) => n.kind === "pattern-conformance");
  const disabledProp = props.find((p) => p.name === "disabled");

  const lines: string[] = [
    `// GENERATED by loom-emit-react. Do not edit by hand.`,
    unsupported.length > 0
      ? `// Unsupported by this backend: ${unsupported.map((n) => n.id).join(", ")}`
      : undefined,
    `import * as React from "react";`,
    component.transitions.length > 0 ? `import { evaluate } from "loom-expr";` : undefined,
    ``,
  ].filter((l): l is string => l !== undefined);

  if (component.transitions.length > 0) {
    lines.push(`const __machine: any = ${machineLiteral(component)};`, ``);
  }

  lines.push(`export interface ${componentName}Props {`);
  for (const prop of props) {
    lines.push(`  /** ${prop.id} */`);
    lines.push(`  ${prop.name}?: ${loomTypeToTs(prop.valueType)};`);
  }
  for (const event of events) {
    lines.push(`  /** ${event.id} */`);
    lines.push(`  on${capitalize(event.name)}?: (payload: ${loomTypeToTs(event.payloadType)}) => void;`);
  }
  for (const slot of slots) {
    lines.push(`  /** ${slot.id} */`);
    lines.push(`  ${slotPropName(slot.name)}?: React.ReactNode;`);
  }
  lines.push(`}`, ``);

  lines.push(`export function ${componentName}(props: ${componentName}Props): React.ReactElement {`);
  const destructured = props.map((p) => `${p.name} = ${JSON.stringify(p.defaultValue ?? null)}`);
  if (destructured.length > 0 || slots.length > 0) {
    const parts = [...destructured, ...slots.map((s) => slotPropName(s.name))];
    lines.push(`  const { ${parts.join(", ")} } = props;`);
  }

  if (component.states.length > 0) {
    lines.push(`  const [state, setState] = React.useState<string>(__machine.states[0]?.id);`);
    lines.push(``);
    lines.push(`  const dispatch = (eventName: string) => {`);
    lines.push(`    const env: any = { ${props.map((p) => p.name).join(", ")} };`);
    lines.push(`    const transition = __machine.transitions.find(`);
    lines.push(
      `      (t: any) => t.from === state && t.trigger?.kind === "event" && t.trigger?.name === eventName && (!t.guard || evaluate(t.guard, env) === true)`
    );
    lines.push(`    );`);
    lines.push(`    if (transition) setState(transition.to);`);
    lines.push(`  };`);
    lines.push(``);
  }

  lines.push(`  return (`);
  lines.push(`    <div`);
  lines.push(`      data-loom-component=${JSON.stringify(component.name)}`);
  if (component.states.length > 0) lines.push(`      data-state={state}`);
  if (pattern) lines.push(`      role=${JSON.stringify(pattern.pattern)}`);
  if (disabledProp) lines.push(`      aria-disabled={disabled}`);
  if (component.transitions.length > 0) lines.push(`      onClick={() => dispatch("click")}`);
  lines.push(`    >`);
  for (const slot of slots) {
    const varName = slotPropName(slot.name);
    if (slot.name === "default") {
      lines.push(`      {children}`);
    } else {
      lines.push(`      <div data-loom-slot=${JSON.stringify(slot.name)}>{${varName}}</div>`);
    }
  }
  lines.push(`    </div>`);
  lines.push(`  );`);
  lines.push(`}`, ``);

  return [{ path: `${componentName}.tsx`, contents: lines.join("\n") }];
}
