import type { ComponentNode, EmittedFile } from "loom-ir";
import { partClassName } from "loom-emit-styles";
import { loomTypeToTs } from "./loomTypeToTs.js";

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}

function pascalCase(slug: string): string {
  return slug.split("-").map(capitalize).join("");
}

/** Slot/prop names come from spec slugs and may contain hyphens, which aren't valid in a JS identifier. */
function camelCase(slug: string): string {
  const [first, ...rest] = slug.split("-");
  return [first, ...rest.map(capitalize)].join("");
}

/** The default slot maps to React's built-in `children`; every other slot becomes its own named prop. */
function slotPropName(slotName: string): string {
  return slotName === "default" ? "children" : camelCase(slotName);
}

function stateLiteral(state: ComponentNode["states"][number]): string {
  return JSON.stringify({ id: state.name, ...state.flags });
}

/**
 * One `new Transition({...})` call, guard included as `Guard.from(expr)` —
 * states are plain data (no behavior to encapsulate), but a transition's
 * matching logic and a guard's evaluation are exactly what these classes
 * exist to own, so they're instantiated explicitly rather than left as
 * anonymous nested object literals.
 */
function transitionLines(transition: ComponentNode["transitions"][number], indent: string): string[] {
  const lines = [
    `${indent}new Transition({`,
    `${indent}  id: ${JSON.stringify(transition.name)},`,
    `${indent}  from: ${JSON.stringify(transition.from)},`,
    `${indent}  to: ${JSON.stringify(transition.to)},`,
    `${indent}  trigger: ${JSON.stringify(transition.trigger)},`,
  ];
  if (transition.guard) lines.push(`${indent}  guard: Guard.from(${JSON.stringify(transition.guard)}),`);
  lines.push(`${indent}}),`);
  return lines;
}

/** `const __machine = new LoomMachine({ ... })`, formatted as readable multi-line source rather than one JSON line. */
function machineLines(component: ComponentNode): string[] {
  const lines: string[] = [`const __machine = new LoomMachine({`, `  states: [`];
  for (const state of component.states) lines.push(`    ${stateLiteral(state)},`);
  lines.push(`  ],`, `  transitions: [`);
  for (const transition of component.transitions) lines.push(...transitionLines(transition, "    "));
  lines.push(`  ],`, `});`, ``);
  return lines;
}

/**
 * Compiles a `ComponentNode` to a minimal React function component (§4/§14
 * step 5 — the first framework target).
 *
 * Declarations become a typed props interface. A `SlotNode` named
 * `"default"` maps to React's built-in `children`; any other slot becomes
 * its own `React.ReactNode` prop. If the component has a machine, it's
 * instantiated at runtime as a loom-expr `LoomMachine` — the same
 * interpreter loom-emit-tests reuses for generated tests, now wrapped in a
 * typed class instead of an untyped literal — rather than transpiling each
 * guard into bespoke JS. Only a generic `click` interaction is wired up for
 * now (key/pointer triggers are a backend TODO); `MethodNode`s have no
 * React rendering strategy yet and are skipped rather than failing the
 * whole emission (§14 step 5's "skip, don't throw" contract). If any `part`
 * (root or a slot) carries a `TokenRefNode`/`LayoutIntentNode`, its DOM node
 * gets a `className` from `loom-emit-styles`' `partClassName` — the same
 * naming function the CSS backend uses to generate the matching selector —
 * and the file imports the sibling `<Component>.css` loom-emit-styles emits.
 */
export function emitReact(component: ComponentNode): EmittedFile[] {
  const componentName = pascalCase(component.name);
  const unsupported = component.declarations.filter((d) => d.kind === "method");
  for (const node of unsupported) {
    // eslint-disable-next-line no-console
    console.warn(`[loom-emit-react] '${node.id}' (kind: method) is unsupported by this backend; skipped.`);
  }

  const props = component.declarations.filter((d) => d.kind === "prop");
  const events = component.declarations.filter((d) => d.kind === "event");
  const slots = component.declarations.filter((d) => d.kind === "slot");
  const pattern = component.a11y.find((n) => n.kind === "pattern-conformance");
  const disabledProp = props.find((p) => p.name === "disabled");
  // `VisualConformanceNode` carries no CSS (§ Style scope), so it doesn't count toward "this part is styled."
  const styledParts = new Set(component.style.filter((n) => n.kind !== "visual-conformance").map((n) => n.part));

  const lines: string[] = [
    `// GENERATED by loom-emit-react. Do not edit by hand.`,
    unsupported.length > 0
      ? `// Unsupported by this backend: ${unsupported.map((n) => n.id).join(", ")}`
      : undefined,
    `import * as React from "react";`,
    component.transitions.length > 0 ? `import { LoomMachine, Transition, Guard } from "loom-expr";` : undefined,
    styledParts.size > 0 ? `import "./${componentName}.css";` : undefined,
    ``,
  ].filter((l): l is string => l !== undefined);

  if (component.transitions.length > 0) {
    lines.push(...machineLines(component));
  }

  lines.push(`export interface ${componentName}Props {`);
  for (const prop of props) {
    lines.push(`  /** ${prop.id} */`);
    lines.push(`  ${prop.name}?: ${loomTypeToTs(prop.valueType)};`);
  }
  for (const event of events) {
    lines.push(`  /** ${event.id} */`);
    lines.push(`  on${capitalize(event.name)}?: (payload: ${loomTypeToTs(event.payloadType)}) => void;`);
  }
  for (const slot of slots) {
    lines.push(`  /** ${slot.id} */`);
    lines.push(`  ${slotPropName(slot.name)}?: React.ReactNode;`);
  }
  lines.push(`}`, ``);

  lines.push(`export function ${componentName}(props: ${componentName}Props): React.ReactElement {`);
  const destructured = props.map((p) => `${p.name} = ${JSON.stringify(p.defaultValue ?? null)}`);
  if (destructured.length > 0 || slots.length > 0) {
    const parts = [...destructured, ...slots.map((s) => slotPropName(s.name))];
    lines.push(`  const { ${parts.join(", ")} } = props;`);
  }

  if (component.states.length > 0) {
    lines.push(`  const [state, setState] = React.useState<string>(__machine.initialState);`);
    lines.push(``);
    lines.push(`  const dispatch = (eventName: string) => {`);
    lines.push(`    const env: any = { ${props.map((p) => p.name).join(", ")} };`);
    lines.push(`    const next = __machine.dispatch(state, eventName, env);`);
    lines.push(`    if (next) setState(next);`);
    lines.push(`  };`);
    lines.push(``);
  }

  lines.push(`  return (`);
  lines.push(`    <div`);
  lines.push(`      data-loom-component=${JSON.stringify(component.name)}`);
  if (styledParts.has("root")) lines.push(`      className=${JSON.stringify(partClassName(component.name, "root"))}`);
  if (component.states.length > 0) lines.push(`      data-state={state}`);
  if (pattern) lines.push(`      role=${JSON.stringify(pattern.pattern)}`);
  if (disabledProp) lines.push(`      aria-disabled={disabled}`);
  if (component.transitions.length > 0) lines.push(`      onClick={() => dispatch("click")}`);
  lines.push(`    >`);
  for (const slot of slots) {
    const varName = slotPropName(slot.name);
    if (slot.name === "default") {
      lines.push(`      {children}`);
    } else {
      const classAttr = styledParts.has(slot.name)
        ? ` className=${JSON.stringify(partClassName(component.name, slot.name))}`
        : "";
      lines.push(`      <div data-loom-slot=${JSON.stringify(slot.name)}${classAttr}>{${varName}}</div>`);
    }
  }
  lines.push(`    </div>`);
  lines.push(`  );`);
  lines.push(`}`, ``);

  return [{ path: `${componentName}.tsx`, contents: lines.join("\n") }];
}
