import type { ComponentNode, EmittedFile, LayoutIntentNode, TokenRefNode } from "loom-ir";
import { partClassName, tokenCssVar } from "./classNames.js";

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}

function pascalCase(slug: string): string {
  return slug.split("-").map(capitalize).join("");
}

function layoutDeclarations(layout: LayoutIntentNode): string[] {
  const lines = [`  display: ${layout.display};`];
  if (layout.direction && layout.display === "flex") lines.push(`  flex-direction: ${layout.direction};`);
  if (layout.align) lines.push(`  align-items: ${layout.align};`);
  if (layout.justify) lines.push(`  justify-content: ${layout.justify};`);
  if (layout.gapToken) lines.push(`  gap: var(${tokenCssVar(layout.gapToken)});`);
  return lines;
}

/**
 * One rule per styled `part` (§ scope limit: `"root"` or an existing slot
 * name), `property: var(--token)` for each `TokenRefNode` and literal
 * flex/grid declarations for each `LayoutIntentNode`. `VisualConformanceNode`
 * carries no CSS — it's a reference for the visual-regression backend, not a
 * style rule.
 */
export function emitComponentCss(component: ComponentNode): EmittedFile {
  const parts = new Map<string, { tokenRefs: TokenRefNode[]; layout?: LayoutIntentNode }>();
  for (const node of component.style) {
    if (node.kind === "visual-conformance") continue;
    const entry = parts.get(node.part) ?? { tokenRefs: [] };
    if (node.kind === "token-ref") entry.tokenRefs.push(node);
    else entry.layout = node;
    parts.set(node.part, entry);
  }

  const blocks: string[] = [];
  for (const [part, { tokenRefs, layout }] of parts) {
    const declarations = [
      ...tokenRefs.map((ref) => `  ${ref.property}: var(${tokenCssVar(ref.token)});`),
      ...(layout ? layoutDeclarations(layout) : []),
    ];
    if (declarations.length === 0) continue;
    blocks.push(`.${partClassName(component.name, part)} {`, ...declarations, `}`);
  }

  const contents = [`/* GENERATED by loom-emit-styles. Do not edit by hand. */`, ...blocks, ``].join("\n");
  return { path: `${pascalCase(component.name)}.css`, contents };
}
