import type { DesignTokens, TokenGroup, TokenLeaf } from "loom-tokens";
import { isTokenLeaf } from "loom-tokens";
import type { EmittedFile } from "loom-ir";
import { tokenCssVar } from "./classNames.js";

function cssLiteral(leaf: TokenLeaf): string {
  return typeof leaf.$value === "string" ? leaf.$value : String(leaf.$value);
}

function collectDeclarations(group: TokenGroup, pathSegments: readonly string[], out: string[]): void {
  for (const [key, node] of Object.entries(group)) {
    const path = [...pathSegments, key];
    if (isTokenLeaf(node)) {
      out.push(`  ${tokenCssVar(path.join("."))}: ${cssLiteral(node)};`);
    } else {
      collectDeclarations(node, path, out);
    }
  }
}

/**
 * Renders the whole `DesignTokens` tree as a single `:root` block of custom
 * properties (`--color-surface-default: #F5F5F5;`). This is the one file
 * every generated component stylesheet references via `var(...)` — never a
 * literal value — so retheming means editing tokens, not component CSS.
 */
export function emitTokensCss(tokens: DesignTokens): EmittedFile {
  const declarations: string[] = [];
  collectDeclarations(tokens, [], declarations);
  const contents = [`/* GENERATED by loom-emit-styles. Do not edit by hand. */`, `:root {`, ...declarations, `}`, ``].join(
    "\n"
  );
  return { path: "tokens.css", contents };
}
